# Generated by Django 3.0.7 on 2022-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200525_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='med_reps',
            field=models.ImageField(blank=True, null=True, upload_to='profile/med_reps'),
        ),
    ]
