# Generated by Django 3.0.7 on 2022-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20220123_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='med_reps',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
